<?php
require 'vendor/autoload.php';

// Read PEM keys generated by OpenSSL CLI
$privateKeyPem = file_get_contents('vapid_private.pem');
$publicKeyPem  = file_get_contents('vapid_public.pem');

$privateKey = openssl_pkey_get_private($privateKeyPem);
$details    = openssl_pkey_get_details($privateKey);

// EC private key d value (raw 32 bytes)
$d = $details['ec']['d'];

// EC public key: uncompressed point = 0x04 + x (32 bytes) + y (32 bytes)
$x = $details['ec']['x'];
$y = $details['ec']['y'];

// Pad to 32 bytes
$x = str_pad($x, 32, "\x00", STR_PAD_LEFT);
$y = str_pad($y, 32, "\x00", STR_PAD_LEFT);
$d = str_pad($d, 32, "\x00", STR_PAD_LEFT);

$publicKeyUncompressed = "\x04" . $x . $y;

$base64url = fn($data) => rtrim(strtr(base64_encode($data), '+/', '-_'), '=');

echo 'VAPID_PUBLIC_KEY='  . $base64url($publicKeyUncompressed) . PHP_EOL;
echo 'VAPID_PRIVATE_KEY=' . $base64url($d) . PHP_EOL;

